language: groovy
jdk:
- oraclejdk7
sudo: false
branches:
  only:
  - master
before_install:
 - wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
 - chmod +x ala_common.sh
 - source ./ala_common.sh

 - ala_travis_grails_setup_env

script:
 - ala_travis_grails_build

env:
  global:
  - secure: jXzO65/r5abRXh7c1Yg2O6gb//L4/czD7F9dKkl+agHTqiftvUfcHw7uAM7QMC/IvrJeDrHNcHbD2jIKqIJIJjc6g/SmuQUzHzDwYHkDhOFSruSqiDQEq5daNuv64HLLbCqwrDvk8BKJ4LkvZ9mvJ96ExksVaNsbpzlufKWD4dM=
  - secure: TA7lwfE84oJ2nkSQf9smfbS7goTL6pYrY1AnE9ZJGSbQwe0fZMGbmkbM9YMzuNKnDLu2kY6l5a2WXOl4iw3SGcJqams046YZ04f9cvMqzhxpjCtpU7uehxTbIc9VbwMHSwoSKLtUMZTD1jYSK17PRlDo9I+p4T/KZ5EY5sPl7dQ=
