language: groovy
jdk:
- oraclejdk8
sudo: false
branches:
  only:
  - master
  - hotfix
  - bs3-with-grails3
#  - nzvh-test
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'

env:
  global:
  - secure: jXzO65/r5abRXh7c1Yg2O6gb//L4/czD7F9dKkl+agHTqiftvUfcHw7uAM7QMC/IvrJeDrHNcHbD2jIKqIJIJjc6g/SmuQUzHzDwYHkDhOFSruSqiDQEq5daNuv64HLLbCqwrDvk8BKJ4LkvZ9mvJ96ExksVaNsbpzlufKWD4dM=
  - secure: TA7lwfE84oJ2nkSQf9smfbS7goTL6pYrY1AnE9ZJGSbQwe0fZMGbmkbM9YMzuNKnDLu2kY6l5a2WXOl4iw3SGcJqams046YZ04f9cvMqzhxpjCtpU7uehxTbIc9VbwMHSwoSKLtUMZTD1jYSK17PRlDo9I+p4T/KZ5EY5sPl7dQ=
