---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.hub
    config:
        locations:
            - file:/data/avh-hub/config/avh-hub-config.properties
            - file:/data/avh-hub/config/avh-hub-config.yml
            - file:/data/avh-hub/config/avh-hub-config.groovy
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities.
        # Disabled by default for performance reasons.
        autowire: false
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    plugins:
        twitterbootstrap:
            fixtaglib: true
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
        description: 'The Australasian Virtual Herbarium'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: true
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true
---

#logging:
#  config: /data/avh-hub/config/logback.groovy

headerAndFooter:
  excludeBootstrapCss: false
  excludeAlaStylesCss: false
  baseURL: "https://www.ala.org.au/commonui-bs3"


speciesGroupsIgnore: "Animals,Arthropods,Bacteria,Crustaceans,Dicots,Insects,Molluscs,Protozoa"

bie:
  baseUrl: "http://bie.ala.org.au/"
  searchPath: "/search"
  autocompleteHints: "fq='kingdom:Plantae'"

biocache:
  baseUrl: "http://biocache.ala.org.au/ws"
  apiKey: "api-key-to-use"
  queryContext: "data_hub_uid:dh2" # data hub uid
  groupedFacetsUrl: "file:///data/avh-hub/config/grouped_facets_avh.json"

spatial:
  baseURL: "http://spatial.ala.org.au/"

ala:
  baseURL: "http://www.ala.org.au"

collections:
  baseUrl: "http://collections.ala.org.au"

dataQualityChecksUrl: "https://docs.google.com/spreadsheet/pub?key=0AjNtzhUIIHeNdHJOYk1SYWE4dU1BMWZmb2hiTjlYQlE&single=true&gid=0&output=csv"

clubRoleForHub: "ROLE_ADMIN"

skin:
    layout: "avh"
    orgNameLong: "Australia's Virtual Herbarium"
    orgNameShort: "AVH"
    includeBaseUrl: true
    headerUrl: "classpath:resources/generic-header.jsp" # can be external URL
    footerUrl: "classpath:resources/generic-footer.jsp" # can be external URL
    fluidLayout: true
    useAlaBie: true
    taxaLinks:
       baseUrl:  "http://bie.ala.org.au/species/"
privacyPolicy: "http://www.ala.org.au/about/terms-of-use/privacy-policy/"

map:
    pointColour: "df4a21"
    zoomOutsideScopedRegion: false
    defaultLatitude: "-27.6"
    defaultLongitude: "141.0"
    defaultZoom: "4"

security:
    cas:
        uriFilterPattern: '/admin/.*,/registration/editAccount,/my-profile,/my-profile/,/myprofile/,/myprofile,/profile/.*,/admin/,/admin,/registration/update,/registration/update/.*,/monitoring,/monitoring/*,/registration/disableAccount/.*,/registration/disableAccount,/admin/admin/downloadUsersCsvFile,/alaAdmin.*'

#server:
#    contextPath: /avh-hub
#    port: 8080

environments:
    development:
        grails:
            serverURL: "https://devt.ala.org.au:8080/avh-hub"
        security:
            cas:
                appServerName: "https://auth.ala.org.au"
    test:
        security:
            cas:
                appServerName: "https://auth.ala.org.au"
    production:
        grails:
            serverURL: "https://avh.ala.org.au"
        security:
            cas:
                appServerName: "https://auth.ala.org.au"
